name: pdf_uploader_app
description: A Flutter app to upload PDFs to Supabase
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  file_picker: ^10.3.1
  path_provider: 2.1.5
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
